// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Nj_pXPemwmA_B1vlFmsJ7FkhA1XFK4s',
    appId: '1:390555985671:web:05bf5a7b377a88c888c7a2',
    messagingSenderId: '390555985671',
    projectId: 'civilhelp-prod',
    authDomain: 'civilhelp-prod.firebaseapp.com',
    storageBucket: 'civilhelp-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsQY6OEJUWPHCfoUidDEeOtzuwJeA1d0',
    appId: '1:390555985671:android:9aae9b7f605db67e88c7a2',
    messagingSenderId: '390555985671',
    projectId: 'civilhelp-prod',
    storageBucket: 'civilhelp-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcWa1HQHP4Xkib0mR2f_vpb-sGYvI1HE',
    appId: '1:390555985671:ios:2bd1c0eef834c7b688c7a2',
    messagingSenderId: '390555985671',
    projectId: 'civilhelp-prod',
    storageBucket: 'civilhelp-prod.firebasestorage.app',
    androidClientId: '390555985671-motodk1fr37fss10hpt50fsuhmuddlsd.apps.googleusercontent.com',
    iosClientId: '390555985671-4rlhgqjm4uav2k8esfqgm7rq57ar7654.apps.googleusercontent.com',
    iosBundleId: 'com.example.civilhelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlcWa1HQHP4Xkib0mR2f_vpb-sGYvI1HE',
    appId: '1:390555985671:ios:2bd1c0eef834c7b688c7a2',
    messagingSenderId: '390555985671',
    projectId: 'civilhelp-prod',
    storageBucket: 'civilhelp-prod.firebasestorage.app',
    androidClientId: '390555985671-motodk1fr37fss10hpt50fsuhmuddlsd.apps.googleusercontent.com',
    iosClientId: '390555985671-4rlhgqjm4uav2k8esfqgm7rq57ar7654.apps.googleusercontent.com',
    iosBundleId: 'com.example.civilhelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Nj_pXPemwmA_B1vlFmsJ7FkhA1XFK4s',
    appId: '1:390555985671:web:c9701664accb85ed88c7a2',
    messagingSenderId: '390555985671',
    projectId: 'civilhelp-prod',
    authDomain: 'civilhelp-prod.firebaseapp.com',
    storageBucket: 'civilhelp-prod.firebasestorage.app',
  );

}